/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gg.sef.view;

import com.gg.sef.persistence.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ggomes
 */
public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
        BuscarUsuario();
        BuscarUsuarioGeral();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        recusuarios = new javax.swing.JTable();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        recgeral = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addTab("Cadastro", jTabbedPane2);

        recusuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CPF", "USUARIO", "SISTEMA"
            }
        ));
        recusuarios.setToolTipText("");
        recusuarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(recusuarios);

        jTabbedPane3.addTab("", jScrollPane1);

        jTabbedPane1.addTab("Busca usuário", jTabbedPane3);

        recgeral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CPF", "NOME", "CARGO", "SISTEMA", "ORGAO"
            }
        ));
        jScrollPane2.setViewportView(recgeral);

        jTabbedPane4.addTab("", jScrollPane2);

        jTabbedPane1.addTab("Geral", jTabbedPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable recgeral;
    private javax.swing.JTable recusuarios;
    // End of variables declaration//GEN-END:variables
public void BuscarUsuario() {
        try {
            Connection con = ConnectionFactory.getConnection("mysql");
            
            String sql = "select CONCAT(SUBSTRING(usuario.cpf,1,3),'.',\n" +
"              SUBSTRING(usuario.cpf,4,3),'.',\n" +
"              SUBSTRING(usuario.cpf,7,3),'-',\n" +
"              SUBSTRING(usuario.cpf,10,2)) AS cpf, nome, sistema from usuario,  user_sis, sistema  where usuario.cpf = user_sis.cpf and sistema.id = user_sis.id";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel model = (DefaultTableModel) recusuarios.getModel();
            model.setNumRows(0);
            while (rs.next()) {
                String[] linha = {rs.getString("cpf"), rs.getString("nome").toUpperCase(), rs.getString("sistema").toUpperCase()};
                model.addRow(linha);
            }

            stmt.close();
            con.close();

        } catch (SQLException ex) {
            System.out.print(ex);
        } catch (ClassNotFoundException ex) {
             System.out.print(ex);
        }
    
    }


public void BuscarUsuarioGeral() {
        try {
            Connection con = ConnectionFactory.getConnection("mysql");
            
            String sql = "SELECT CONCAT(SUBSTRING(usuario.cpf,1,3),'.',\n" +
"              SUBSTRING(usuario.cpf,4,3),'.',\n" +
"              SUBSTRING(usuario.cpf,7,3),'-',\n" +
"              SUBSTRING(usuario.cpf,10,2)) AS cpf , nome, cargo, sistema , orgao  FROM usuario,  user_sis, sistema , orgao, user_org, cargo, user_cargo\n" +
            "WHERE usuario.cpf = user_sis.cpf AND sistema.id = user_sis.id AND usuario.cpf = user_org.cpf AND orgao.id = user_org.id\n" +
            "AND usuario.cpf = user_cargo.cpf AND cargo.id = user_cargo.id";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel model = (DefaultTableModel) recgeral.getModel();
            model.setNumRows(0);
            while (rs.next()) {
                String[] linha = {rs.getString("cpf"), rs.getString("nome").toUpperCase(), rs.getString("sistema").toUpperCase(), rs.getString("cargo").toUpperCase(), rs.getString("orgao").toUpperCase()};
                model.addRow(linha);
            }

            stmt.close();
            con.close();

        } catch (SQLException ex) {
            System.out.print(ex);
        } catch (ClassNotFoundException ex) {
             System.out.print(ex);
        }
    
    }   
}
